main: eu.cloudnetservice.simplenametag.SimpleNameTagPlugin
api-version: 1.13
version: ${nametag.version}
author: TheMeinerLP
depend: [CloudNetAPI]
description: CloudNet SimpleNameTagSystem for the Central server
website: https://cloudnetservice.eu/
name: SimpleNameTag

